# Generated by Django 3.2 on 2021-05-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stacjaradiowa',
            name='kategoria',
            field=models.ManyToManyField(blank=True, through='stacje.KategorieStacji', to='stacje.Kategoria'),
        ),
        migrations.AlterField(
            model_name='stacjaradiowa',
            name='miasto',
            field=models.ManyToManyField(blank=True, through='stacje.StacjeWMiescie', to='stacje.Miasto'),
        ),
        migrations.AlterField(
            model_name='stacjaradiowa',
            name='zatrudnieni',
            field=models.ManyToManyField(blank=True, through='stacje.ZatrudnieniPrezenterzy', to='stacje.Prezenter'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adres e-mail'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='nazwa',
            field=models.CharField(max_length=30, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='ulubioneSieci',
            field=models.ManyToManyField(blank=True, through='stacje.UlubioneSieci', to='stacje.SiecRadiowa'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='ulubioneStacje',
            field=models.ManyToManyField(blank=True, through='stacje.UlubioneStacje', to='stacje.StacjaRadiowa'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nazwa użytkownika'),
        ),
    ]
