# Generated by Django 3.2 on 2021-05-28 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stacje', '0002_auto_20210528_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artykul',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artykul',
            name='tresc',
            field=models.TextField(verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='artykul',
            name='tytul',
            field=models.CharField(max_length=100, verbose_name='Tytuł'),
        ),
    ]
