# Generated by Django 3.2 on 2021-05-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacje', '0003_auto_20210528_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artykul',
            name='url',
            field=models.SlugField(blank=True, editable=False, max_length=500),
        ),
    ]
