# Generated by Django 3.2 on 2021-05-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacje', '0004_alter_artykul_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='url',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
