# Generated by Django 3.2 on 2021-05-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacje', '0005_alter_uzytkownik_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siecradiowa',
            name='url',
            field=models.SlugField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='spolkamediowa',
            name='url',
            field=models.SlugField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='stacjaradiowa',
            name='url',
            field=models.SlugField(blank=True, editable=False, max_length=500),
        ),
    ]
