# Generated by Django 3.2 on 2021-05-31 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stacje', '0006_auto_20210528_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artykul',
            options={'verbose_name': 'Artykuł', 'verbose_name_plural': 'Artykuły'},
        ),
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='miasto',
            options={'verbose_name_plural': 'Miasta'},
        ),
        migrations.AlterModelOptions(
            name='prezenter',
            options={'verbose_name_plural': 'Prezenterzy'},
        ),
        migrations.AlterModelOptions(
            name='prezes',
            options={'verbose_name_plural': 'Prezesowie'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name_plural': 'Programy'},
        ),
        migrations.AlterModelOptions(
            name='siecradiowa',
            options={'verbose_name': 'Sieć radiowa', 'verbose_name_plural': 'Sieci radiowe'},
        ),
        migrations.AlterModelOptions(
            name='slowokluczowe',
            options={'verbose_name': 'Słowo kluczowe', 'verbose_name_plural': 'Słowa kluczowe'},
        ),
        migrations.AlterModelOptions(
            name='spolkamediowa',
            options={'verbose_name': 'Spółka mediowa', 'verbose_name_plural': 'Spółki mediowe'},
        ),
        migrations.AlterModelOptions(
            name='stacjaradiowa',
            options={'verbose_name': 'Stacja radiowa', 'verbose_name_plural': 'Stacje radiowe'},
        ),
        migrations.AlterModelOptions(
            name='uzytkownik',
            options={'verbose_name': 'Użytkownik', 'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.AddField(
            model_name='stacjaradiowa',
            name='siecRadiowa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stacje.siecradiowa', verbose_name='Sieć radiowa'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='kodPocztowy',
            field=models.CharField(max_length=7, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='numerBudynku',
            field=models.CharField(max_length=10, verbose_name='Numery budynku'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='numerLokalu',
            field=models.IntegerField(blank=True, verbose_name='Numer lokalu'),
        ),
        migrations.AlterField(
            model_name='artykul',
            name='dataWstawienia',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data wstawienia'),
        ),
        migrations.AlterField(
            model_name='artykul',
            name='wyroznienie',
            field=models.BooleanField(default=False, verbose_name='Wyróżnienie'),
        ),
        migrations.AlterField(
            model_name='miasto',
            name='wojewodztwo',
            field=models.CharField(choices=[('WM', 'WARMIŃSKO-MAZURSKIE'), ('PL', 'PODLASKIE'), ('OS', 'OPOLSKIE'), ('PR', 'POMORSKIE'), ('ZP', 'ZACHODNIO-POMORSKIE'), ('WP', 'WIELKOPOLSKIE'), ('SK', 'ŚWIĘTOKRZYSKIE'), ('SL', 'ŚLĄSKIE'), ('DS', 'DOLNOŚLĄSKIE'), ('KP', 'KUJAWSKO-POMORSKIE'), ('LO', 'ŁÓDZKIE'), ('LBE', 'LUBELSKIE'), ('LBU', 'LUBUSKIE'), ('MZ', 'MAZOWIECKIE'), ('MP', 'MAŁOPOLSKIE'), ('PK', 'PODKARPACKIE')], max_length=30, verbose_name='Województwo'),
        ),
        migrations.AlterField(
            model_name='prezenter',
            name='imie',
            field=models.CharField(max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='prezes',
            name='imie',
            field=models.CharField(max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='program',
            name='godzinaRozpoczecia',
            field=models.TimeField(verbose_name='Godzina rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='program',
            name='godzinaZakonczenia',
            field=models.TimeField(verbose_name='Godzina zakończenia'),
        ),
        migrations.AlterField(
            model_name='program',
            name='nadawaneProgramy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacje.stacjaradiowa', verbose_name='Nadawane programy'),
        ),
        migrations.AlterField(
            model_name='program',
            name='prowadzacy',
            field=models.ManyToManyField(through='stacje.ProwadzacyProgramu', to='stacje.Prezenter', verbose_name='Prowadzący'),
        ),
        migrations.AlterField(
            model_name='program',
            name='tytul',
            field=models.CharField(max_length=30, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='siecradiowa',
            name='adresSiedziby',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stacje.adres', verbose_name='Adres siedziby'),
        ),
        migrations.AlterField(
            model_name='siecradiowa',
            name='dataZakonczenia',
            field=models.DateField(blank=True, verbose_name='Data zakończenia działalności'),
        ),
        migrations.AlterField(
            model_name='siecradiowa',
            name='dataZalozenia',
            field=models.DateField(verbose_name='Data założenia'),
        ),
        migrations.AlterField(
            model_name='siecradiowa',
            name='okresDzialalnosci',
            field=models.DurationField(blank=True, verbose_name='Okres działalności'),
        ),
        migrations.AlterField(
            model_name='spolkamediowa',
            name='adresSiedziby',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stacje.adres', verbose_name='Adres siedziby'),
        ),
        migrations.AlterField(
            model_name='spolkamediowa',
            name='dataZakonczenia',
            field=models.DateField(blank=True, verbose_name='Data zakończenia działalności'),
        ),
        migrations.AlterField(
            model_name='spolkamediowa',
            name='dataZalozenia',
            field=models.DateField(verbose_name='Data założenia'),
        ),
        migrations.AlterField(
            model_name='spolkamediowa',
            name='okresDzialalnosci',
            field=models.DurationField(blank=True, verbose_name='Okres działalności'),
        ),
        migrations.AlterField(
            model_name='stacjaradiowa',
            name='czestotliwosc',
            field=models.CharField(max_length=10, verbose_name='Częstotliwość'),
        ),
        migrations.AlterField(
            model_name='stacjaradiowa',
            name='dataZakonczenia',
            field=models.DateField(blank=True, verbose_name='Data zakończenia działalności'),
        ),
        migrations.AlterField(
            model_name='stacjaradiowa',
            name='dataZalozenia',
            field=models.DateField(verbose_name='Data założenia'),
        ),
        migrations.AlterField(
            model_name='stacjaradiowa',
            name='okresDzialalnosci',
            field=models.DurationField(blank=True, verbose_name='Okres działalności'),
        ),
        migrations.AlterField(
            model_name='stacjaradiowa',
            name='spolkaMediowa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='stacje.spolkamediowa', verbose_name='Spółka mediowa'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='dataUtworzeniaKonta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data utworzenia konta'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='ulubioneSieci',
            field=models.ManyToManyField(blank=True, through='stacje.UlubioneSieci', to='stacje.SiecRadiowa', verbose_name='Ulubione sieci'),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='ulubioneStacje',
            field=models.ManyToManyField(blank=True, through='stacje.UlubioneStacje', to='stacje.StacjaRadiowa', verbose_name='Ulubione stacje'),
        ),
    ]
