# Generated by Django 3.2 on 2021-05-31 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stacje', '0007_auto_20210531_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siecradiowa',
            name='dataZakonczenia',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakończenia działalności'),
        ),
        migrations.AlterField(
            model_name='siecradiowa',
            name='okresDzialalnosci',
            field=models.DurationField(blank=True, null=True, verbose_name='Okres działalności'),
        ),
        migrations.AlterField(
            model_name='siecradiowa',
            name='prezes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='stacje.prezes'),
        ),
    ]
