# Generated by Django 3.2 on 2021-05-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacje', '0008_auto_20210531_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='numerBudynku',
            field=models.CharField(max_length=10, verbose_name='Numer budynku'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='numerLokalu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numer lokalu'),
        ),
    ]
