# Generated by Django 3.2 on 2021-05-31 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stacje', '0009_auto_20210531_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spolkamediowa',
            name='adresSiedziby',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stacje.adres', verbose_name='Adres siedziby'),
        ),
    ]
